### ISSUE TITLE
Is there any way you can add studio api?

### ISSUE THREAD

**Issue by ghost** [webdev03/periscope-api#1]
Because I'm thinking of also giving Studio info to make this site a bit more different from the others. Link: https://api.scratch.mit.edu/studios/xxxxxx/ (xxxxx = id) The downside is that the user will have to enter the id, but it should be good, right?

**Comment by imdevarsh** [comment]
Yes I can add this in!

**Comment by ghost** [comment]
Thank you!

**Comment by imdevarsh** [comment]
I think it can stay open until I do it

**Comment by ghost** [comment]
OK
